name: food_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  firebase_storage: ^11.3.1
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  lottie: ^2.6.0
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.0.5
  smooth_page_indicator: ^1.1.0
  uuid: ^4.1.0
  widget_and_text_animator: ^1.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
